DROP DATABASE IF EXISTS  proyecto;
CREATE DATABASE IF NOT EXISTS proyecto;
USE proyecto;

DROP TABLE IF EXISTS registro;
CREATE TABLE registro(
	id INT UNSIGNED AUTO_INCREMENT,
	nombre TEXT NOT NULL,
	correo VARCHAR(50) NOT NULL,
	clave VARCHAR(100) NOT NULL,
	fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY(id),
	CONSTRAINT UNIQUE(correo) 
);

DROP TABLE IF EXISTS login;
CREATE TABLE login(
	id INT UNSIGNED AUTO_INCREMENT,
	correo VARCHAR(50) NOT NULL,
	clave VARCHAR(100) NOT NULL,
	fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY(id),
	CONSTRAINT UNIQUE(correo)
);